// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnV9LPNtKc8VjD7CmAiqg5pKBxSOCrM94',
    appId: '1:34949700392:web:b3cbc3b7084abfec2b4e1d',
    messagingSenderId: '34949700392',
    projectId: 'chat-flutter-app-618e9',
    authDomain: 'chat-flutter-app-618e9.firebaseapp.com',
    storageBucket: 'chat-flutter-app-618e9.appspot.com',
    measurementId: 'G-ZKGTS2PM2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1iQZfLtys_g4BtTahRXL1c7_FedfBbVk',
    appId: '1:34949700392:android:0c0a35195379597d2b4e1d',
    messagingSenderId: '34949700392',
    projectId: 'chat-flutter-app-618e9',
    storageBucket: 'chat-flutter-app-618e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0_CmagMZTdHqv6PfNYeaoRHuUUssCEaY',
    appId: '1:34949700392:ios:545a1f07cdc1dee92b4e1d',
    messagingSenderId: '34949700392',
    projectId: 'chat-flutter-app-618e9',
    storageBucket: 'chat-flutter-app-618e9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0_CmagMZTdHqv6PfNYeaoRHuUUssCEaY',
    appId: '1:34949700392:ios:545a1f07cdc1dee92b4e1d',
    messagingSenderId: '34949700392',
    projectId: 'chat-flutter-app-618e9',
    storageBucket: 'chat-flutter-app-618e9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnV9LPNtKc8VjD7CmAiqg5pKBxSOCrM94',
    appId: '1:34949700392:web:1ed6dbea8d70f53c2b4e1d',
    messagingSenderId: '34949700392',
    projectId: 'chat-flutter-app-618e9',
    authDomain: 'chat-flutter-app-618e9.firebaseapp.com',
    storageBucket: 'chat-flutter-app-618e9.appspot.com',
    measurementId: 'G-HK9FL0DNV8',
  );
}
